### ISSUE TITLE
regeneratorRuntime is not defined (babel-polyfill)

### ISSUE THREAD

**Issue by pshenmic** [binance-chain/javascript-sdk#125]
Code:
```
const BnbApiClient = require("@binance-chain/javascript-sdk")
const bnbClient = new BnbApiClient("https://dex.binance.org")
```

Error:
```
~/project/node_modules/@binance-chain/javascript-sdk/lib/client/index.js:54
regeneratorRuntime.mark(function _callee(tx, signMsg) {
^

    ReferenceError: regeneratorRuntime is not defined
    at ~/project/node_modules/@binance-chain/javascript-sdk/lib/client/index.js:54:3
    at Object.<anonymous> (~/project/node_modules/@binance-chain/javascript-sdk/lib/client/index.js:72:2)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (~/project/node_modules/@binance-chain/javascript-sdk/lib/index.js:3:38)
```

Code crashes on first line, when trying to load sdk. I'm pretty sure #111 is related

**Comment by pshenmic** [comment]
When I manually add babel-polyfill in dependencies and load up it manually, everything works as expected:

```
require("babel-polyfill")
const BnbApiClient = require("@binance-chain/javascript-sdk")
const bnbClient = new BnbApiClient("https://dex.binance.org")
```

**Comment by notatestuser** [comment]
Thank you. Could you please try with `v2.12.0`?

**Comment by pshenmic** [comment]
Thanks, now its working
