### ISSUE TITLE
When I make transfer I got the below issue

### ISSUE THREAD

**Issue by suriyaprakashosiz** [binance-chain/javascript-sdk#169]
TypeError: unencodedPubKey.x.toArrayLike is not a function
    at Transaction._serializePubKey (/var/www/html/node_modules/@binance-chain/javascript-sdk/lib/tx/index.js:203:84)
    at Transaction.addSignature (/var/www/html/node_modules/@binance-chain/javascript-sdk/lib/tx/index.js:137:21)
    at Transaction.sign (/var/www/html/node_modules/@binance-chain/javascript-sdk/lib/tx/index.js:160:12)

Could you please help me to resolve this?

**Comment by notatestuser** [comment]
Did you set the private key on the client?

**Comment by MindfulMe** [comment]
how to set it? Where to get private key if we only have keystore.txt file? Salt does not work as intended. You do not mention anything about it in wiki.

**Comment by notatestuser** [comment]
A keystore file isn’t a private key, but it contains one. You can load the private key from a keystore file using the function made for that purpose:

https://github.com/binance-chain/javascript-sdk/wiki/API-Documentation#module_crypto.getPrivateKeyFromKeyStore
