### ISSUE TITLE
Error: chain id should not be null

### ISSUE THREAD

**Issue by mohammedaliarsh** [binance-chain/javascript-sdk#183]
While doing parallel transfers i am getting this error

Error: chain id should not be null
    at new Transaction (C:\\bnbridge.exchange\sdk\node_modules\@binance-chain\javascript-sdk\lib\tx\index.js:73:13)
    at BncClient._callee9$ (C:bnbridge.exchange\sdk\node_modules\@binance-chain\javascript-sdk\lib\client\index.js:774:22)
    at tryCatch (C:\\bnbridge.exchange\sdk\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\\bnbridge.exchange\sdk\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (C:\bnbridge.exchange\sdk\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (C:\bnbridge.exchange\sdk\node_modules\@binance-chain\javascript-sdk\lib\client\index.js:26:103)
    at _next (C:\bnbridge.exchange\sdk\node_modules\@binance-chain\javascript-sdk\lib\client\index.js:28:194)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by huangsuyu** [comment]
Hello, @mohammedaliarsh 

Can you share more information about how you got this error please?

Thanks !

**Comment by mohammedaliarsh** [comment]
when i am calling transfer method parallel i am getting this kind of error..
it if is only a single transfer it is working fine.

**Comment by notatestuser** [comment]
Please be sure to call `await client.initChain()` first.
