### ISSUE TITLE
Ledger Example: couldn't import ledger module 

### ISSUE THREAD

**Issue by Sotatek-TuNguyen** [binance-chain/javascript-sdk#213]
I tried the Ledger example and got the following error:
```
{ LedgerApp: [Function: LedgerApp],
  app: [Function: LedgerApp],
  transports:
   { u2f:
      { [Function: TransportU2F] isSupported: [Function], list: [Function], listen: [Function] },
     wble:
      { [Function: BluetoothTransport]
        isSupported: [Function],
        observeAvailability: [Function],
        list: [Function],
        disconnect: [Function] },
     node:
      { [Function: TransportNodeHid]
        isSupported: [Function],
        list: [Function],
        setListenDevicesDebounce: [Function],
        setListenDevicesPollingSkip: [Function],
        setListenDevicesDebug: [Function],
        listen: [Function] } } }
/home/tuna/Sotatek/BinanceChain/wallet2wallet.js:3
const ledger = sdk.ledger
                   ^

TypeError: sdk.ledger is not a function
    at Object.<anonymous> (/home/tuna/Sotatek/BinanceChain/wallet2wallet.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
the snippet code causes the error was: 
```
const sdk = require("@binance-chain/javascript-sdk")
console.log(sdk.ledger)
const ledger = sdk.ledger
```
Could you explain it for me! I wonder if it's was the error caused by nodejs or not?

**Comment by notatestuser** [comment]
`sdk.ledger` is indeed not a function. You might want to use: `new sdk.ledger.app(transport)`

**Comment by Sotatek-TuNguyen** [comment]
> `sdk.ledger` is indeed not a function. You might want to use: `new sdk.ledger.app(transport)`

Sorry for late reply, but what actually `transport` in `new sdk.ledger.app(transport)` is?

**Comment by notatestuser** [comment]
The Ledger example should be helpful here:

https://github.com/binance-chain/javascript-sdk/wiki/API-Examples#ledger




________________________________
