### ISSUE TITLE
BNB transfer does not work on mainnet

### ISSUE THREAD

**Issue by MindfulMe** [binance-chain/javascript-sdk#264]
### Your first example does not work on mainnet 
https://github.com/binance-chain/javascript-sdk/wiki/API-Examples.

I send from this address **bnb1xakdtqe4vydk8q9n5n8z52f9qlkgghfanye3yz** to **bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23**. 

### The error message is completely irrelevant!

I get the issue:
```

(node:16382) UnhandledPromiseRejectionWarning: Error: unable to query the address on the blockchain. try sending it some funds first: bnb1t6x8k7r2yw33r6tvhcstwnr7qcv7ual74v5mmv
    at BncClient._callee5$ (/Users/rostyslav/Desktop/meta-server/node_modules/@binance-chain/javascript-sdk/lib/client/index.js:394:23)
    at tryCatch (/Users/rostyslav/Desktop/meta-server/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/rostyslav/Desktop/meta-server/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as throw] (/Users/rostyslav/Desktop/meta-server/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/rostyslav/Desktop/meta-server/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/Users/rostyslav/Desktop/meta-server/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by MindfulMe** [comment]
It has enough funds, wtf?
https://explorer.binance.org/address/bnb1xakdtqe4vydk8q9n5n8z52f9qlkgghfanye3yz

<img width="1367" alt="Screenshot 2020-06-07 at 13 59 40" src="https://user-images.githubusercontent.com/26275425/83967088-2327f180-a8c7-11ea-91b4-8d7c017ef1c6.png">

**Comment by MindfulMe** [comment]
I use salt from keystore.txt as my private key. On testnet no errors, it works - on mainnet it is fucked.

**Comment by MindfulMe** [comment]
I assume that my salt is not the private key, and I can't get the private key from keystore.txt it gives me some testnet bullshit when I recover

**Comment by MindfulMe** [comment]
You have to provide more examples, since such errors that your module gives impossible to find what the fuck could the errors mean

**Comment by MindfulMe** [comment]
neither on Google or StackOverflow, XLM has far better coverage

**Comment by MindfulMe** [comment]
Ok, solved. I used recovery from keystore.txt and got the testnet shit and took that testnet private key and used the private key to transfer.

**Comment by MindfulMe** [comment]
And your lib is a complete piece of shit, with lack of examples and comments
