### ISSUE TITLE
Npm i fails: usb@1.5.0 from the ledjer dep does not compiles under ubuntu

### ISSUE THREAD

**Issue by pitersky** [binance-chain/javascript-sdk#55]
I made

```
git clone https://github.com/binance-chain/javascript-sdk
cd javascript-sdk
npm i
```

Installation fails with (last lines):

```
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.5.0/usb_bindings-v1.5.0-node-v67-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.5.0 and node@11.4.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.
libusb.target.mk:140: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/wave/.nvm/versions/node/v11.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/home/wave/.nvm/versions/node/v11.4.0/bin/node" "/home/wave/.nvm/versions/node/v11.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd /home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/wave/.nvm/versions/node/v11.4.0/bin/node /home/wave/.nvm/versions/node/v11.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Linux 4.15.0-45-generic
node-pre-gyp ERR! command "/home/wave/.nvm/versions/node/v11.4.0/bin/node" "/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/wave/.nvm/versions/node/v11.4.0/bin/node /home/wave/.nvm/versions/node/v11.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/wave/projects/current/atomic/etc/bnb-issues-2/javascript-sdk/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
npm WARN @binance-chain/javascript-sdk@2.4.12 No repository field.
npm WARN @binance-chain/javascript-sdk@2.4.12 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usb@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wave/.npm/_logs/2019-02-18T06_50_02_055Z-debug.log``
```

Seems that ```@ledgerhq/hw-transport-node-hid``` from ```package.json``` has ```node-usb``` dep that does not  have prebuild libraries for linux. The issue in node-usb is open ```https://github.com/tessel/node-usb/issues/78```

My ```uname -a```:

```
uname -a 
Linux wave-TM1604 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by notatestuser** [comment]
Hi @pitersky, if you are using a Debian-based system, you might be missing some dependencies.

Could you please try:-

```bash
sudo apt-get install libudev-dev libusb-dev usbutils
```

**Comment by pitersky** [comment]
Works. Thank you!
